export const CITIES = [
  'Delhi',
  'Mumbai',
  'Bangalore',
  'Hyderabad',
  'Chennai',
  'Kolkata',
  'Pune',
  'Ahmedabad',
  'Jaipur',
  'Lucknow',
  'Chandigarh',
  'Indore',
  'Coimbatore',
  'Visakhapatnam',
  'Surat',
  'Vadodara',
  'Goa',
  'Kochi',
  'Thiruvananthapuram',
  'Bhopal',
  'Nagpur',
  'Raipur',
  'Patna',
  'Ranchi',
];

export const NICHES = [
  'Fashion',
  'Beauty',
  'Food & Beverage',
  'Fitness',
  'Health & Wellness',
  'Lifestyle',
  'Travel',
  'Technology',
  'Gaming',
  'Education',
  'Finance',
  'Parenting',
  'Home & Decor',
  'Automotive',
  'Pets',
  'Entertainment',
  'Photography',
  'Cooking',
  'DIY & Craft',
  'Books & Reading',
];

export const BRAND_CATEGORIES = [
  'Fashion & Apparel',
  'Beauty & Cosmetics',
  'Food & Beverage',
  'Health & Wellness',
  'Electronics & Gadgets',
  'Home & Decor',
  'Fitness & Sports',
  'Travel & Tourism',
  'Education',
  'Finance & Banking',
  'Automotive',
  'Real Estate',
  'Entertainment',
  'Pets & Pet Care',
  'Sustainable & Eco',
  'Photography & Art',
  'Furniture',
  'Jewelry',
  'Retail & E-commerce',
  'Services',
];

export const CONTENT_TYPES = [
  'Instagram Post',
  'Instagram Reel',
  'Instagram Story',
  'TikTok Video',
  'YouTube Short',
  'Blog Post',
  'Podcast Mention',
  'Unboxing Video',
  'Tutorial',
  'Review',
  'Testimonial',
  'Product Demo',
  'Multiple Posts',
];

export const CAMPAIGN_STATUS = {
  ACTIVE: 'active',
  PAUSED: 'paused',
  COMPLETED: 'completed',
  DRAFT: 'draft',
} as const;

export const DEAL_STATUS = {
  PENDING: 'pending',
  ESCROW_HELD: 'escrow_held',
  CONTENT_SUBMITTED: 'content_submitted',
  REVISION_REQUESTED: 'revision_requested',
  APPROVED: 'approved',
  RELEASED: 'released',
  REFUNDED: 'refunded',
  DISPUTED: 'disputed',
} as const;

export const APPLICATION_STATUS = {
  PENDING: 'pending',
  ACCEPTED: 'accepted',
  REJECTED: 'rejected',
} as const;
